### ISSUE TITLE
Your thingamajig doesn't work on Debian Testing 32 bit

### ISSUE THREAD

**Issue by szero** [EZ3CHI3L/Eternity#2]
Do I need to have AMD hardware in order to run this? Here's my screenfetch:
```
         _,met$$$$$gg.           szeraton@leetpad
      ,g$$$$$$$$$$$$$$$P.        OS: Debian testing buster
    ,g$$P""       """Y$$.".      Kernel: i686 Linux 4.12.0-1-686-pae
   ,$$P'              `$$$.      Uptime: 1d 20m
  ',$$P       ,ggs.     `$$b:    Packages: 2406
  `d$$'     ,$P"'   .    $$$     Shell: zsh 5.4.2
   $$P      d$'     ,    $$P     Resolution: 1680x1050
   $$:      $$.   -    ,d$$'     DE: XFCE
   $$\;      Y$b._   _,d$P'      WM: Xfwm4
   Y$$.    `.`"Y$$$$P"'          WM Theme: Arc-Dark
   `$$b      "-.__               GTK Theme: Arc-Dark [GTK2]
    `Y$$                         Icon Theme: Arc
     `Y$$.                       Font: Sans 11
       `$$b.                     CPU: Intel Core2 Duo P8700 @ 2x 2.534GHz [52.0°C]
         `Y$$b.                  GPU: Mesa DRI Mobile Intel® GM45 Express Chipset x86/MMX/SSE2
            `"Y$b._              RAM: 2368MiB / 3935MiB
                `""""
```

Here's the error it gives:
```
$ ./eternity ~/Desktop/christmas-rare256b.png
[ STBI ] loaded /home/szeraton/Desktop/christmas-rare256b.png
3.2.1 X11 GLX EGL clock_gettime /dev/js Xf86vm shared
Compiled against GLFW 3.2.1
Running against GLFW 3.2.1
GLX: Failed to create context: GLXBadFBConfig
[ ETERNITY ] /home/szeraton/Gites/Eternity/src/libeternity/src/engine.c:60 in et_engine_init()
Could not create window
```

**Comment by EZ3CHI3L** [comment]
It looks like you're using Mesa, which is a software renderer. You need a driver with hardware acceleration. I'm gonna try to make it work without HW accel sooner or later tho.

**Comment by szero** [comment]
I compiled GLFW from [this](https://github.com/glfw/glfw/commit/d79056fc27ff693ba0968d626574e421707845c0) branch that was supposed to enable software rendering but after adding this window hint: `glfwWindowHint(GLFW_CONTEXT_RENDERER, GLFW_SOFTWARE_RENDERER);` the program still errors out the same way.

**Comment by EZ3CHI3L** [comment]
Can you post the output of `glxinfo | grep OpenGL`

**Comment by szero** [comment]
```
$ glxinfo | grep OpenGL
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Mobile Intel® GM45 Express Chipset x86/MMX/SSE2
OpenGL version string: 2.1 Mesa 13.0.6
OpenGL shading language version string: 1.20
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 13.0.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
OpenGL ES profile extensions:
```

**Comment by EZ3CHI3L** [comment]
It looks like your OpenGL version is too old, you could try forcing a 2.1 context but that's about it.

**Comment by szero** [comment]
Hoi again, I made [this](https://gist.github.com/Szero/bdb6a70a549a0284a15434c59bb59b64) patch that forces OpenGL 2.1 context and GLSL 1.2. The program doesn't error out now and the window is being created but everything is black and the OpenGL version is reported as `GL_INVALID_VALUE`. Here's full [screencap](https://files.catbox.moe/j50exp.png) of it. Can you at least tell me what should I read to be able to debug this?

**Comment by szero** [comment]
Hi, I made [it]( https://pomf.pyonpyon.moe/zqwfro.png) work finally. Thing was busted because API for my version of GLSL is not compatible with newest versions. Here's the [patch](https://gist.github.com/Szero/104f38785c6c54ddf493a7d1f75a2213). Would you merge PR that adds support for older intel iGPUs?

**Comment by EZ3CHI3L** [comment]
Very nice. I don't plan on targeting compatibility profiles on the master branch yet, but you can go ahead and create a PR to the compatibility branch I just made and I will merge it.
